---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/signup":
    post:
      summary: Creates a user registration
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
      requestBody:
        content:
          application/json:
            schema:
              type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
basePath: "/api/v1"
